name: Publish phenix Docker images
on:
  push:
    branches: ['**']
  repository_dispatch:
    types: [apps-update]
jobs:
  push-to-ghcr:
    name: Push phenix Docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || contains(github.event.head_commit.message, 'BUILD DOCKER IMAGES') }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get short SHA
        id: short
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            PHENIX_VERSION=${{ steps.short.outputs.branch }}
            PHENIX_COMMIT=${{ steps.short.outputs.sha }}
            APPS_REPO=${{ github.event_name == 'repository_dispatch' && github.event.client_payload.repo || 'sandia-minimega/phenix-apps' }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/phenix:${{ steps.short.outputs.sha }}
            ghcr.io/${{ github.repository }}/phenix:${{ steps.short.outputs.branch }}
  push-jit-to-ghcr:
    name: Push phenix JIT Docker image to GitHub Packages
    needs: push-to-ghcr
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'main' || contains(github.event.head_commit.message, 'BUILD DOCKER IMAGES') }}
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get short SHA
        id: short
        run: |
          echo "::set-output name=sha::$(git rev-parse --short HEAD)"
          echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container image
        uses: docker/build-push-action@v2
        with:
          context: docker/jit
          file: docker/jit/Dockerfile
          build-args: |
            PHENIX_REPO=${{ github.repository }}
            PHENIX_TAG=${{ steps.short.outputs.branch }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/phenix-jit-ui:${{ steps.short.outputs.sha }}
            ghcr.io/${{ github.repository }}/phenix-jit-ui:${{ steps.short.outputs.branch }}
